sudo: false
language: cpp

env:
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

before_install:
 - source .travis/setenv_lua.sh

install:
 - if [[ "$TRAVIS_OS_NAME" = "linux" && "$CXX" = "g++" ]]; then
       export CXX="g++-4.8" CC="gcc-4.8";
   fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
  - make -j2 test
