sudo: false
language: generic

env:
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - g++-5
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

script:
  - make -j2 test
